# Generated by Django 3.2.7 on 2021-09-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filmwork',
            table='"content"."film_work"',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='"content"."genre"',
        ),
        migrations.AlterModelTable(
            name='genrefilmwork',
            table='"content"."genre_film_work"',
        ),
        migrations.AlterModelTable(
            name='person',
            table='"content"."person"',
        ),
        migrations.AlterModelTable(
            name='personfilmwork',
            table='"content"."person_film_work"',
        ),
    ]
