services:
  movies_admin:
    build:
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/movies_admin/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
  movies_etl:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/movies_etl/:/usr/src/app/
    env_file:
      - ./.env.dev
  elasticsearch:
    ports:
      - "9200:9200"
    env_file:
      - ./.env.dev
  postgres:
    env_file:
      - ./.env.dev
