version: '3.9'

volumes:
  postgres_data:

services:
  movies_admin:
    build:
      context: ./services/movies_admin/
      dockerfile: Dockerfile.dev
    container_name: movies_admin
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - ./services/movies_admin/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./variables/.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/movies_admin/entrypoint.initdb.sh:/docker-entrypoint-initdb.d/entrypoint-initdb.sh
    env_file:
      - ./variables/.env.dev.db
