version: "3.9"

services:
  postgresql:
    image: postgres
    restart: always
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - /postgresql/data:/var/lib/postgresql/data

  django:
    build: .
    command: >
      bash -c "sleep 5
      && python manage.py migrate
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/var/movies/static
    expose:
      - "8000"
    depends_on:
      - postgresql

  upload_data:
    build: ./sqlite_to_postgres/.
    command: >
      bash -c "sleep 15
      && python load_data.py"
    depends_on:
      - db
      - web

  nginx:
    build: ./build/nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static:/var/movies/static

volumes:
  static:
  postgresql: