volumes:
  movies_admin_media_data:
  movies_admin_static_data:

services:
  movies_admin:
    build:
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - movies_admin_media_data:/home/app/web/mediafiles
      - movies_admin_static_data:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  movies_film_etl:
    build:
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
  movies_person_etl:
    build:
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
  movies_genre_etl:
    build:
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
  movies_async_api:
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    build:
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file:
      - ./.env.prod
  elasticsearch:
    expose:
      - 9200
    env_file:
      - ./.env.prod
  postgres:
    env_file:
      - ./.env.prod
  redis:
    expose:
      - 6379
    env_file:
      - ./.env.prod
  nginx:
    build: ./services/nginx
    container_name: nginx
    volumes:
      - movies_admin_media_data:/home/app/web/mediafiles
      - movies_admin_static_data:/home/app/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - movies_admin
