version: '3.9'

services:
  movies_admin:
    build:
      context: ./services/movies_admin/
      dockerfile: Dockerfile.prod
    container_name: movies_admin
    command: gunicorn configs.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./variables/.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/movies_admin/entrypoint-initdb.sh:/docker-entrypoint-initdb.d/entrypoint-initdb.sh
    env_file:
      - ./variables/.env.prod.db
  nginx:
    build: ./services/nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - movies_admin

volumes:
  postgres_data:
  static_volume:
  media_volume: