services:
  movies_admin:
    build:
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/movies_admin/:/usr/src/app/
    ports:
      - "1337:8000"
    env_file:
      - ./.env.dev
  movies_film_etl:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/movies_etl/:/usr/src/app/
    env_file:
      - ./.env.dev
  movies_person_etl:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/movies_etl/:/usr/src/app/
    env_file:
      - ./.env.dev
  movies_genre_etl:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/movies_etl/:/usr/src/app/
    env_file:
      - ./.env.dev
  movies_async_api:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
  movies_auth:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
  elasticsearch:
    ports:
      - "9200:9200"
    env_file:
      - ./.env.dev
  postgres:
    env_file:
      - ./.env.dev
  redis:
    ports:
      - "6379:6379"
    env_file:
      - ./.env.dev
