tags:
- "Roles"
summary: "Add new role"
parameters:
- description: "Access token"
  in: "header"
  name: "Authorization"
  required: true
  schema:
    $ref: "#/definitions/JWT"
- description: "Role object that needs to be added"
  in: "body"
  name: "body"
  required: true
  schema:
    $ref: "#/definitions/NewRoleInfo"
responses:
  201:
    description: "Added Successfully"
    schema:
      $ref: "#/definitions/RoleInfo"
  401:
    description: "Superuser requered"
  409:
    description: "Role already exists"
  422:
    description: "Bad Authorization header"