tags:
- "roles"
summary: "Delete role"
parameters:
- in: "header"
  name: "Authorization"
  description: "Access token"
  required: true
  schema:
    $ref: "#/definitions/JWT"
- in: "body"
  name: "body"
  description: "Role object that needs to be deleted"
  schema:
    $ref: "#/definitions/Role"
responses:
  200:
    description: "Sucess deleted"
  401:
    description: "Superuser requered"
  409:
    description: "Roles does not exist"
  422:
    description: "Bad Authorization header"