tags:
- "roles"
summary: "Get roles"
parameters:
- in: "header"
  name: "Authorization"
  description: "Access token"
  required: true
  schema:
    $ref: "#/definitions/JWT"
responses:
  200:
    description: "Roles"
    schema:
      $ref: "#/definitions/Roles"
  401:
    description: "Superuser requered"
  422:
    description: "Bad Authorization header"