tags:
- "Roles"
summary: "Get role info"
parameters:
- description: "Role name"
  in: "path"
  name: "role_name"
  type: "string"
  required: true
- description: "Access token"
  in: "header"
  name: "Authorization"
  required: true
  schema:
    $ref: "#/definitions/JWT"
responses:
  200:
    description: "Roles"
    schema:
      $ref: "#/definitions/RoleInfo"
  401:
    description: "Superuser requered"
  404:
    description: "Role not found"
  422:
    description: "Bad Authorization header"