tags:
- "roles"
summary: "Patch role"
parameters:
- in: "header"
  name: "Authorization"
  description: "Access token"
  required: true
  schema:
    $ref: "#/definitions/JWT"
- in: "body"
  name: "body"
  description: "Update role schema"
  schema:
    $ref: "#/definitions/PatchRole"
responses:
  200:
    description: "Sucess patched"
  401:
    description: "Superuser requered"
  409:
    description: "Roles does not exist"
  422:
    description: "Bad Authorization header"