"""Permissions

Revision ID: 313d1749f85f
Revises: 
Create Date: 2021-11-19 20:05:56.779401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '313d1749f85f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index(op.f('ix_content_permissions_name'), 'permissions', ['name'], unique=True, schema='content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_permissions_name'), table_name='permissions', schema='content')
    op.drop_table('permissions', schema='content')
    # ### end Alembic commands ###
