"""Users-Permissions relation

Revision ID: 4dda19e49682
Revises: d76c8a0b3b45
Create Date: 2021-11-21 13:20:13.535562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from core import config
from models.additions.partitions import get_create_user_permission_partitions_cmds, get_drop_partition_cmd

# revision identifiers, used by Alembic.
revision = '4dda19e49682'
down_revision = 'd76c8a0b3b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permission',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('permission_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['content.permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id'),
    schema='content',
    postgresql_partition_by='HASH (user_id)'
    )

    for cmd in get_create_user_permission_partitions_cmds(config.DB_USERS_PARTITIONS_NUM):
        op.execute(cmd)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for remainder in range(config.DB_USERS_PARTITIONS_NUM):
        op.execute(get_drop_partition_cmd('user_permission', remainder))

    op.drop_table('user_permission', schema='content')
    # ### end Alembic commands ###
