"""Roles

Revision ID: 69dabc5b05fb
Revises: 4dda19e49682
Create Date: 2021-11-21 18:16:13.964618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69dabc5b05fb'
down_revision = '4dda19e49682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index(op.f('ix_content_roles_name'), 'roles', ['name'], unique=True, schema='content')
    op.create_table('role_permission',
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('permission_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['content.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['content.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='content'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission', schema='content')
    op.drop_index(op.f('ix_content_roles_name'), table_name='roles', schema='content')
    op.drop_table('roles', schema='content')
    # ### end Alembic commands ###
