"""user logins

Revision ID: 7f0efe9ac34e
Revises: 1e419f04b9d1
Create Date: 2021-11-24 08:16:59.704449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f0efe9ac34e'
down_revision = '1e419f04b9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_logins',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('user', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['content.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_logins', schema='content')
    # ### end Alembic commands ###
