"""Users

Revision ID: d76c8a0b3b45
Revises: 313d1749f85f
Create Date: 2021-11-19 20:15:55.429993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from core import config
from models.additions.partitions import get_create_users_partitions_cmds, get_drop_partition_cmd

# revision identifiers, used by Alembic.
revision = 'd76c8a0b3b45'
down_revision = '313d1749f85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='content',
    postgresql_partition_by='HASH (id)'
    )

    for cmd in get_create_users_partitions_cmds(config.DB_USERS_PARTITIONS_NUM):
        op.execute(cmd)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for remainder in range(config.DB_USERS_PARTITIONS_NUM):
        op.execute(get_drop_partition_cmd('users', remainder))

    op.drop_table('users', schema='content')
    # ### end Alembic commands ###
